{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}
{% set name = "kglab" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "0f651eb79b6da45324dc2a2f38f132e032e1e6c38380b29e36842632bfa6f87a"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - chocolate
    - fsspec
    - gcsfs
    - gensim
    - gputil
    - icecream
    - matplotlib
    - networkx
    - numpy
    - owlrl
    - pandas
    - pslpython
    - pyarrow
    - pylev
    - pyshacl
    - python
    - python-dateutil
    - pyvis
    - rdflib
    - rdflib-jsonld
    - scikit-learn
    - urlpath
  run:
    - chocolate
    - fsspec
    - gcsfs
    - gensim
    - gputil
    - icecream
    - matplotlib
    - networkx
    - numpy
    - owlrl
    - pandas
    - pslpython
    - pyarrow
    - pylev
    - pyshacl
    - python
    - python-dateutil
    - pyvis
    - rdflib
    - rdflib-jsonld
    - scikit-learn
    - urlpath

test:
  imports:
    - kglab

about:
  home: http://github.com/DerwenAI/kglab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A simple abstraction layer in Python for building knowledge graphs"
  doc_url: https://derwen.ai/docs/kgl/
  dev_url: http://github.com/DerwenAI/kglab

extra:
  recipe-maintainers:
    - ceteri
