site_name: kglab
site_url: https://github.com/DerwenAI/kglab
site_description: Graph-Based Data Science
site_author: kglab contributors and Derwen, Inc.
repo_url: https://github.com/DerwenAI/kglab
repo_name: DerwenAI/kglab


nav:
    - Home: index.md
    - User Guide:
        - Getting Started: start.md
        - What is a Knowledge Graph?: what.md
        - Use Cases: use_case.md
        - Concepts: concepts.md
        - Package Reference: ref.md
        - Dependencies: depend.md
        - About The Author(s): author.md
    - Tutorial:
        - Setup:
            - Installation: tutorial.md
            - Data sources: ex0_0.md
        - Construction:
            - Build an RDF graph using `RDFlib`: ex1_0.md
            - Leverage the `kglab` abstraction layer: ex1_1.md
        - Serialization:
            - Build a medium size KG from a CSV dataset: ex2_0.md
        - Visualization:
            - Interactive graph visualization with `PyVis`: ex3_0.md
        - Querying:
            - Run SPARQL queries: ex4_0.md
        - Validation:
            - SHACL validation with `pySHACL`: ex5_0.md
        - Graph Algorithms:
            - Graph algorithms with `NetworkX`: ex6_0.md
            - Discover community structure using `iGraph` and `leidenalg`: ex6_1.md
        - Inference:
            - Inference capabilities: infer.md
            - Measurement and inference: ex7_0.md
            - Statistical relational learning with `pslpython`: ex7_1.md
        - Embedding:
            - Vector embedding with `gensim`: ex8_0.md
        - Topology:
            - (TBD) Evolved Shape Prediction: stub.ipynb
        - Distributed Systems:
            - (TBD) Distributed processing with `RAPIDS` and `Ray`: stub.ipynb
    - Glossary: glossary.md
    - Bibliography: biblio.md
    - Acknowledgements: ack.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - mknotebooks
  - git-revision-date

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      toc_depth: 3
      permalink: true

use_directory_urls: true
copyright: Source code and documentation are <strong><a href="https://github.com/DerwenAI/kglab/blob/main/LICENSE" target="_blank">licensed</a></strong> under an MIT License; Copyright (c) 2020-2021 <strong><a href="https://derwen.ai/" target="_blank">Derwen, Inc.</a></strong>
