site_name: kglab
site_url: https://github.com/DerwenAI/kglab
site_description: Graph-Based Data Science
site_author: kglab team

nav:
    - Home: index.md
    - Test: foo.md
    - User Guide:
        - Getting Started: start.md
        - What Is A Knowledge Graph?: what.md
        - Concepts: concepts.md
        - Use Cases: use_case.md
        - API Reference: api.md
        - Dependencies: depend.md
        - Acknowledgements: ack.md
        - About The Author: author.md
        - Glossary: glossary.md
        - Bibliography: biblio.md
    - Tutorial:
        - Setup:
            - Learn to use kglab: tutorial.md
            - Data sources: ex00.ipynb
        - Construction:
            - Build an RDF graph using `RDFlib`: ex01.ipynb
            - Leverage the `kglab` abstraction layer: ex02.ipynb
        - Serialization:
            - Build a medium size KG from a CSV dataset: ex04.ipynb
        - Visualization:
            - Interactive graph visualization with `PyVis`: ex03.ipynb
        - Querying:
            - Run SPARQL queries: ex05.ipynb
        - Validation:
            - SHACL validation with `pySHACL`: ex06.ipynb
        - Graph Algorithms:
            - Graph algorithms with `NetworkX`: ex07.ipynb
            - Discover community structure using `iGraph` and `leidenalg`: ex11.ipynb
        - Inference:
            - Inference capabilities: infer.md
            - Measurement and inference: ex10.ipynb
            - Statistical relational learning with `pslpython`: ex08.ipynb
        - Embedding:
            - Vector embedding with `gensim`: ex09.ipynb
        - Topology:
            - Evolved Shape Prediction: stub.ipynb
        - Distributed Systems:
            - Distributed processing with `RAPIDS` and `Ray`: stub.ipynb

theme:
  name: material

plugins:
  - mknotebooks

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - codehilite

use_directory_urls: true
copyright: Source code and documentation are licensed under an MIT License; Copyright (c) 2020-2021 Derwen, Inc.
