site_name: kglab

nav:
    - Home: index.md
    - What: what.md
    - Why: why.md
    - Background: background.md
    - Tutorial: tutorial.md
    - Inference: infer.md

plugins:
  - mknotebooks

markdown_extensions:
  - codehilite
