site_name: kglab
site_url: https://github.com/DerwenAI/kglab
site_description: Graph-Based Data Science
site_author: kglab contributors and Derwen, Inc.

nav:
    - Home: index.md
    - User Guide:
        - Getting Started: start.md
        - What Is A Knowledge Graph?: what.md
        - Concepts: concepts.md
        - Use Cases: use_case.md
        - Package Reference: ref.md
        - Dependencies: depend.md
        - Acknowledgements: ack.md
        - About The Author: author.md
        - Glossary: glossary.md
        - Bibliography: biblio.md
    - Tutorial:
        - Setup:
            - Installation: tutorial.md
            - Data sources: ex00.md
        - Construction:
            - Build an RDF graph using `RDFlib`: ex01.md
            - Leverage the `kglab` abstraction layer: ex02.md
        - Serialization:
            - Build a medium size KG from a CSV dataset: ex04.md
        - Visualization:
            - Interactive graph visualization with `PyVis`: ex03.md
        - Querying:
            - Run SPARQL queries: ex05.md
        - Validation:
            - SHACL validation with `pySHACL`: ex06.md
        - Graph Algorithms:
            - Graph algorithms with `NetworkX`: ex07.md
            - Discover community structure using `iGraph` and `leidenalg`: ex11.md
        - Inference:
            - Inference capabilities: infer.md
            - Measurement and inference: ex10.md
            - Statistical relational learning with `pslpython`: ex08.md
        - Embedding:
            - Vector embedding with `gensim`: ex09.md
        - Topology:
            - Evolved Shape Prediction: stub.ipynb
        - Distributed Systems:
            - Distributed processing with `RAPIDS` and `Ray`: stub.ipynb

theme:
  name: material

plugins:
  - mknotebooks

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite

use_directory_urls: true
copyright: Source code and documentation are <strong><a href="ack/">licensed</a></strong> under an MIT License; Copyright (c) 2020-2021 Derwen, Inc.
